repository:
  allow_squash_merge: true
  allow_rebase_merge: true
  default_branch: master
  private: true

branches:
  - name: master
    protection:
      enforce_admins: true
      required_pull_request_reviews:
        required_approving_review_count: 1
        require_code_owner_reviews: true
        dismiss_stale_reviews: false
        dismissal_restrictions: {}
      required_status_checks:
        strict: true
        contexts: ["code_check"]
      restrictions:
        apps: []
        users: []
        teams: ["@kronostechnologies/dev"]

