repository:
  default_branch: master
  allow_squash_merge: true
  allow_rebase_merge: true

branches:
  - name: master
    protection:
      required_pull_request_reviews:
        enforce_admins: true
        required_approving_review_count: 1
        require_code_owner_reviews: true
        dismissal_restrictions: null
        required_status_checks:
          strict: true
          contexts: ["code_check"]
      restrictions:
        apps: []
        users: []
        teams: ["kronostechnologies/dev"]

